import Head from 'next/head'
import Header from '../components/Header'
import Banner from '../components/Banner'
import { Movie } from '../typin'
import requests from '../utils/requests'
import Row from '../components/Row'
import useAuth from '../hooks/useAuth'
import { useRecoilValue } from 'recoil'
import { modalState } from '../atoms/modalAtoms'
import Modal from '../components/Modal'

interface props {
  netflixOriginals: Movie[],
  trendingNow: Movie[],
  topRated: Movie[],
  actionMovies: Movie[],
  comedyMovies: Movie[],
  horrorMovies: Movie[],
  romanceMovies: Movie[],
  documentaries: Movie[],
}

const Home = ({
  netflixOriginals,
  trendingNow,
  topRated,
  actionMovies,
  comedyMovies,
  horrorMovies,
  romanceMovies,
  documentaries,
}:props ) =>  {

const { loading } = useAuth()
const showModal = useRecoilValue(modalState)
// const showModal = useRecoilValue() the same as using useState const [showModal, setShowModal] = useState(false)the difference is useRecoil we only have to use a customer hook useRecoilValue


if (loading) return null


  return (
    <div className='relative h-screen bg-gradient-to-b lg:h-[140vh]'>
      <Head>
        <title>Home - Netflix</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAASwAAACoCAMAAABt9SM9AAAAbFBMVEUAAAD/AADTAADWAAC+AACjAAC1AADLAADIAACnAACqAACtAADBAACyAADEAACcAAB2AABgAACVAADfAAH4AADpAACLAACQAACFAAB/AABLAABqAAAaAABFAAJbAAEsAAASAAA6AAAlAABTAABsoJ1mAAAGT0lEQVR4nO2d65KbOhCECRgwdxvf95LdzXn/dzwgJGNAanClilS5p/8mSuyv1EjqGWHPE4lEIpFIJBKJRCKRaE2979x6tw/5vXfrbd1Pv7L8X0Af1iHxIXDpkKz88ddVhWCdrUO2ge9SEK788dfV+QhgHaxDeGFdoA+/bEN4YdUpglXZhvDCqqoTgHWyDSGGFW7R1Pq0DCGGlSQIVmYZQgwrhT48WoYwwwpLNLX20yG8sMIsCRGsfDqEGhb04a/pEGZYabhBsHaTIcSwimZqIVj+ZAgvrCRqYB0QrUn0QA0rDQsEaxI98MJKoyJNqqeiB2pYWVoFaGqNowdeWNmm9WGGYI2jB2pY7XqIfDiOHohh5cqHMZpao+iBF1aRR40Pn4oeiGGVnQ+fiB54YUXbTTu1KhgBDqMHZli5Wg+hD4fRAzmsOR8OowdiWHGpfPhE9MALaxOXnQ+XRw/MsDofpsujB2JY/lb7MEKwLg9DmGF1PsywDx+jB2pYxodLowdiWMHdhzB6eKBADUv5cC4CfIgeuGGZfSnsPuqjB2pYdx/CI09xH8INK+7Oh0ujB4GlfLgseiipYTWP+I068sCuh9IMyclhPRU95E5WPLBmo4ebGcINy9c5zbKuB3pYxodLoocoZoel6hYz0YPueoi23LDMeoh9qKOHaOucWiSwjA8XRA+FwNI+XBA9FKXThxyw2uihWw/no4csd04tFljGh7DrQd29TDclPawl0YPqekg3ucuHJLC6fWmxJHpoYTmmFg2sRdFDe206iZw+5IGlfJjg6KHtemhguXzIAkuXxGZ82EYPYeScWjywjA/nuh7CQmDFi6KHuL3BErke8TSwdElsPnqosmZq0cPSPpy7cKFg2X3IBEvvS2t84aJKnT7kgaVLYnPV1o86cfqQDVbrQ3jkqS+J04dEsExpGm+1TtcwcfmQCVY3tdKZI09WOacWH6y56CGowvYRb4sAmWCZkliIjzy104dcsMyRJ0ewIqcPKWHNNJh2PrRED1Sw+tI0PPJULh+SwTI+hNXWjcuHlLCaRzys8rh8yAWrL03DaqvLh2ywzCMeVltLhw8ZYc1GD8aH5LD6KB5WW8PQGj3QwVoUPcR2H/LB0i0iuNpaJ7b1kA1W3yICo4ekmVrTkhgfLONDWG31qySd+pAO1v12yowPQ0sUzwcr3up9Kay2thGgwOp9eENbrTYCnPiQEZaOHm5oF3+0HXn4YN1va17fkA+LcLoeMsLS0cPZQ4/4g2U9ZISlo4ezB3cPlpyGEJZpEbl4fxAsHQE+PrQoYXU+PHseSpctPmSEpbtxL553WeLDmByWmloNrG8EK59ED7ywovYFNCjVOtXdvnTLDas7H9bNn+/Q1ArH+1JOWGpqtbA8dOTZjn3IDgsV8k/j9ZATliqJqfcE75EPk5EPWWE1U6t7qTLy4TiKp4cFo4d6eOQhhdUeeTpYMHpIhz6khbUt9TdH0cMoihdYqFfrOIweWGE1tPQ3h0eeYRQvsDzUUBMMfMgLKza/Rntd7ENaWP4dlod8WKitlvahwPI8VMgfRIC8sPzU/KV3NLUe96XEsPrfrkBHnq4rPldTixdW0MNCvcuPPhRYjX4jHz5E8QKrFTrybFSrlvIhMaz+pbce6pl8iAAFVqtP7ENz5BFYSsiHfVc8MazHn71C0UPvQ4GlBKMHUxITWFooeijvLSICS+kGfWhK0wKrE/KhWQ8FlhaKHkxpWmBpoejh1EUPZSywtFD0oNfDePxjt6+lJ2Ch6EGXprcCSwtFD6fulpjAugsdeboWkVJgGaHoIVZHnrz+J19iLT0DC0UPXYuIwOqFfJiq0rTAuqvGPswKgdULRQ9dafpi+z9eRk/BgtGDatUSWL1Q14PfPrTO/+ArrKfnYKHooV0PC4H1IBQ9tOuhwHoQunDhC6yRQPTQ+vC6+hdYU8/CQq8vSAXWUOjCRVAlAmsg6EOBNRS6cJGFN9uQl9HTsNCFi6ASWEOB6OEosEZC73oodit//HU1hRUYHSLriC/kQw5YQQvpcAgCPy6jsKrPu/ffn/Yh77trlUUb/3CcrIzHV4fVQgriPKrOt/3bz5+nRn//vO2vYbY9mQfZa0c0aVbf9j8ff/3vfH/9d602h9euSItEIpFIJBKJRKK/0//NxYSy2rnhhQAAAABJRU5ErkJggg==" />
      </Head>
      <Header />
      <main className='relative pl-4 pb-24 lg:space-y-24 lg:pl-16'>
      <Banner netflixOriginals= {trendingNow}/>
        <section className='md:space-y-24'>
          {/* continue Watching */}
          {/* My List */ }
          <Row title = 'Trending Now' movies={trendingNow} /> 
          <Row title = 'Top Rated' movies = {topRated} />
          <Row title = 'Action Thriller' movies = {actionMovies} />
          <Row title = 'Comedy' movies = {comedyMovies} />
          <Row title = 'Originals' movies = {netflixOriginals} />
          <Row title = 'Scary Movies' movies = {horrorMovies} />
          <Row title = 'Romance Movies' movies = {romanceMovies} />
          <Row title = 'Documentaries' movies = {documentaries} /> 
        </section>
      </main>
      {showModal && <Modal/>}
    </div>
  )
}

export default Home

export const getServerSideProps = async () =>{
  const [
    netflixOriginals,
    trendingNow,
    topRated,
    actionMovies,
    comedyMovies,
    horrorMovies,
    romanceMovies,
    documentaries,
  ] = await Promise.all([
    fetch(requests.fetchNetflixOriginals).then((res) => res.json()),
    fetch(requests.fetchTrending).then((res) => res.json()),
    fetch(requests.fetchTopRatedMovies).then((res) => res.json()),
    fetch(requests.fetchActionMovies).then((res) => res.json()),
    fetch(requests.fetchComedyMovies).then((res) => res.json()),
    fetch(requests.fetchHorrorMovies).then((res) => res.json()),
    fetch(requests.fetchRomanceMovies).then((res) => res.json()),
    fetch(requests.fetchDocumentaries).then((res) => res.json()),

  ])
  return {
    props: {
      netflixOriginals: netflixOriginals.results,
      trendingNow: trendingNow.results,
      topRated: topRated.results,
      actionMovies: actionMovies.results,
      comedyMovies: comedyMovies.results,
      horrorMovies: horrorMovies.results,
      romanceMovies: romanceMovies.results,
      documentaries: documentaries.results,
    },
  }
}

