import { async } from '@firebase/util'
import Head from 'next/head'
import Image from 'next/image'
import React from 'react'
import { useState } from 'react'
import { SubmitHandler, useForm } from 'react-hook-form'
import useAuth from '../hooks/useAuth'

interface Inputs {
  email: string
  password: string
}

function Login() {
  const [login, setLogin] = useState(false)
  const {signIn, signUp} = useAuth()

  const { register, handleSubmit, formState: { errors } } = useForm<Inputs>();
  const onSubmit: SubmitHandler<Inputs> = async ({email, password}) => {
    if (login){
      await signIn(email, password)
    } else {
      await signUp(email, password)
    }
  };

  return (
    <div className='relative flex h-screen w-screen flex-col bg-black md:items-center md:justify-center md:bg-transparent'>
      <Head>
        <title>Netflix</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAASwAAACoCAMAAABt9SM9AAAAbFBMVEUAAAD/AADTAADWAAC+AACjAAC1AADLAADIAACnAACqAACtAADBAACyAADEAACcAAB2AABgAACVAADfAAH4AADpAACLAACQAACFAAB/AABLAABqAAAaAABFAAJbAAEsAAASAAA6AAAlAABTAABsoJ1mAAAGT0lEQVR4nO2d65KbOhCECRgwdxvf95LdzXn/dzwgJGNAanClilS5p/8mSuyv1EjqGWHPE4lEIpFIJBKJRCKRaE2979x6tw/5vXfrbd1Pv7L8X0Af1iHxIXDpkKz88ddVhWCdrUO2ge9SEK788dfV+QhgHaxDeGFdoA+/bEN4YdUpglXZhvDCqqoTgHWyDSGGFW7R1Pq0DCGGlSQIVmYZQgwrhT48WoYwwwpLNLX20yG8sMIsCRGsfDqEGhb04a/pEGZYabhBsHaTIcSwimZqIVj+ZAgvrCRqYB0QrUn0QA0rDQsEaxI98MJKoyJNqqeiB2pYWVoFaGqNowdeWNmm9WGGYI2jB2pY7XqIfDiOHohh5cqHMZpao+iBF1aRR40Pn4oeiGGVnQ+fiB54YUXbTTu1KhgBDqMHZli5Wg+hD4fRAzmsOR8OowdiWHGpfPhE9MALaxOXnQ+XRw/MsDofpsujB2JY/lb7MEKwLg9DmGF1PsywDx+jB2pYxodLowdiWMHdhzB6eKBADUv5cC4CfIgeuGGZfSnsPuqjB2pYdx/CI09xH8INK+7Oh0ujB4GlfLgseiipYTWP+I068sCuh9IMyclhPRU95E5WPLBmo4ebGcINy9c5zbKuB3pYxodLoocoZoel6hYz0YPueoi23LDMeoh9qKOHaOucWiSwjA8XRA+FwNI+XBA9FKXThxyw2uihWw/no4csd04tFljGh7DrQd29TDclPawl0YPqekg3ucuHJLC6fWmxJHpoYTmmFg2sRdFDe206iZw+5IGlfJjg6KHtemhguXzIAkuXxGZ82EYPYeScWjywjA/nuh7CQmDFi6KHuL3BErke8TSwdElsPnqosmZq0cPSPpy7cKFg2X3IBEvvS2t84aJKnT7kgaVLYnPV1o86cfqQDVbrQ3jkqS+J04dEsExpGm+1TtcwcfmQCVY3tdKZI09WOacWH6y56CGowvYRb4sAmWCZkliIjzy104dcsMyRJ0ewIqcPKWHNNJh2PrRED1Sw+tI0PPJULh+SwTI+hNXWjcuHlLCaRzys8rh8yAWrL03DaqvLh2ywzCMeVltLhw8ZYc1GD8aH5LD6KB5WW8PQGj3QwVoUPcR2H/LB0i0iuNpaJ7b1kA1W3yICo4ekmVrTkhgfLONDWG31qySd+pAO1v12yowPQ0sUzwcr3up9Kay2thGgwOp9eENbrTYCnPiQEZaOHm5oF3+0HXn4YN1va17fkA+LcLoeMsLS0cPZQ4/4g2U9ZISlo4ezB3cPlpyGEJZpEbl4fxAsHQE+PrQoYXU+PHseSpctPmSEpbtxL553WeLDmByWmloNrG8EK59ED7ywovYFNCjVOtXdvnTLDas7H9bNn+/Q1ArH+1JOWGpqtbA8dOTZjn3IDgsV8k/j9ZATliqJqfcE75EPk5EPWWE1U6t7qTLy4TiKp4cFo4d6eOQhhdUeeTpYMHpIhz6khbUt9TdH0cMoihdYqFfrOIweWGE1tPQ3h0eeYRQvsDzUUBMMfMgLKza/Rntd7ENaWP4dlod8WKitlvahwPI8VMgfRIC8sPzU/KV3NLUe96XEsPrfrkBHnq4rPldTixdW0MNCvcuPPhRYjX4jHz5E8QKrFTrybFSrlvIhMaz+pbce6pl8iAAFVqtP7ENz5BFYSsiHfVc8MazHn71C0UPvQ4GlBKMHUxITWFooeijvLSICS+kGfWhK0wKrE/KhWQ8FlhaKHkxpWmBpoejh1EUPZSywtFD0oNfDePxjt6+lJ2Ch6EGXprcCSwtFD6fulpjAugsdeboWkVJgGaHoIVZHnrz+J19iLT0DC0UPXYuIwOqFfJiq0rTAuqvGPswKgdULRQ9dafpi+z9eRk/BgtGDatUSWL1Q14PfPrTO/+ArrKfnYKHooV0PC4H1IBQ9tOuhwHoQunDhC6yRQPTQ+vC6+hdYU8/CQq8vSAXWUOjCRVAlAmsg6EOBNRS6cJGFN9uQl9HTsNCFi6ASWEOB6OEosEZC73oodit//HU1hRUYHSLriC/kQw5YQQvpcAgCPy6jsKrPu/ffn/Yh77trlUUb/3CcrIzHV4fVQgriPKrOt/3bz5+nRn//vO2vYbY9mQfZa0c0aVbf9j8ff/3vfH/9d602h9euSItEIpFIJBKJRKK/0//NxYSy2rnhhQAAAABJRU5ErkJggg==" />
      </Head>
      <Image src="https://rb.gy/p2hphi" 
      layout='fill'
      className='-z-10 !hidden opacity-60 sm:!inline'
      objectFit='cover'
      />
    <img src="https://rb.gy/ulxxee"
          width={100}
          height={100}
          className="absolute left-4 top-4 cursor-pointer object-contain md:left-10 md:top-6" alt='' />
          <form onSubmit={handleSubmit(onSubmit)} 
          className='relative mt-20 space-y-8 rounded bg-black/75 py-10 px-6 sm:mt-0
          md:max-w-md md:px-14'>
            <h1 className='text-4xl font-semibold'>Sign In</h1>
            <div className='space-y-4'>
              <label className='inline-block w-full'>
                <input 
                type="email" 
                placeholder='Email or phone number' 
                className='input'
                {...register("email", {required: 'true'})}  
                // cfr react hook form
                />
                {errors.email && 
                <p className='p-1 text-[13px] font-light text-orange-500'>
                  Please enter a valid email or phone number
                  </p>}
              </label>
              <label className='inline-block w-full'>
                <input 
                type="password" 
                placeholder='Password' 
                className='input'
                {...register("password", {required: 'true'})}/>
                {errors.password && 
                <p className='p-1 text-[13px] font-light text-orange-500'>
                  Your password must contain between 4 and 60 characters
                  </p>}
              </label>
            </div>
            <button className='w-full rounded bg-[#e50914] py-3 font-semibold'onClick={()=> setLogin(true)}>
              Sign In
            </button>
            <div className='text-[gray]'>
              New to Netflix?{" "}
              <button type='submit' className='text-white font-semibold text-14 sm:text-17 hover:underline'
               onClick={() =>setLogin(false)}>
                Sign up now
                </button>
            </div>
          </form>
    </div>
  )
}

export default Login